### ISSUE TITLE
can not play more then one link

### ISSUE THREAD

**Issue by richardmeilinger** [firsttris/repository.sendtokodi.leia#1]
Sending the first link works fine.
When I try to play a second video I get an error.

- Kodi 17.6 Windows link from Youtube
- Plugin version 0.0.66.1
- iOS 11.2.5

17:46:01.248 T:8988   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: attribute of type 'NoneType' is not callable
                                            Traceback (most recent call last):
                                              File "C:\Users\richard\AppData\Roaming\Kodi\addons\plugin.video.sendtokodi\service.py", line 77, in <module>
                                                result = ydl.extract_info(url, download=False)
                                              File "C:\Users\richard\AppData\Roaming\Kodi\addons\plugin.video.sendtokodi\youtube_dl\YoutubeDL.py", line 785, in extract_info
                                                ie_result = ie.extract(url)
                                              File "C:\Users\richard\AppData\Roaming\Kodi\addons\plugin.video.sendtokodi\youtube_dl\extractor\common.py", line 440, in extract
                                                ie_result = self._real_extract(url)
                                              File "C:\Users\richard\AppData\Roaming\Kodi\addons\plugin.video.sendtokodi\youtube_dl\extractor\youtube.py", line 1736, in _real_extract
                                                upload_date = unified_strdate(upload_date)
                                              File "C:\Users\richard\AppData\Roaming\Kodi\addons\plugin.video.sendtokodi\youtube_dl\utils.py", line 1171, in unified_strdate
                                                upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
                                            TypeError: attribute of type 'NoneType' is not callable
                                            -->End of Python script error report<--

**Comment by firsttris** [comment]
hey richard,

it seems that your issue is really a python issue which happens inside [youtube_dl](https://github.com/rg3/youtube-dl)

there are also some issues related to this
https://github.com/rg3/youtube-dl/issues/11362

strange enough since a more recent libreelec version this issue was resolved. (seems they ship a more recent python version).

Do you know which python version kodi is using on windows? (integrated)

best
regards
Tristan

**Comment by richardmeilinger** [comment]
Hey Tristan,

thanks for getting back to me.
Kodi 17.6 on Window is running on Python 2.7.13.

I took a quick look at the utils.py file in youtube_dl and added a the general exception to the unified_strdate function as purposed in the issue rg3/youtube-dl#11362

```
    for expression in date_formats(day_first):
        try:
            upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
        except ValueError:
            pass
        except:
            pass
```

This worked for me.
thanks & best regards Richard

**Comment by anohren** [comment]
@richardmeilinger I forgot to say thanks for the workaround, since I incorporated your solution in https://github.com/firsttris/plugin.video.sendtokodi/pull/11
